repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--config-files=project-config/.cmake-format.py, --in-place]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
      - id: clang-format
        args: [--style=file:project-config/.clang-format]
        # Exclude generated files
        exclude: '^src/kaitai/structs/'